// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa4BnjJ20DpiBsgsuRTTpEzYiD0Z5FesY',
    appId: '1:732076536297:android:9014499f3b8d776c0d5b78',
    messagingSenderId: '732076536297',
    projectId: 'chatapp-9b603',
    storageBucket: 'chatapp-9b603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrBp19VudPxBHsw38w8dtKeFmyMl0nc_s',
    appId: '1:732076536297:ios:684b0c90b8326d6d0d5b78',
    messagingSenderId: '732076536297',
    projectId: 'chatapp-9b603',
    storageBucket: 'chatapp-9b603.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGqQFde1aFK23JNAwTbhIJGCprZFgnmUk',
    appId: '1:732076536297:web:13662c81b3d22a5b0d5b78',
    messagingSenderId: '732076536297',
    projectId: 'chatapp-9b603',
    authDomain: 'chatapp-9b603.firebaseapp.com',
    storageBucket: 'chatapp-9b603.appspot.com',
  );
}
